<template>
  <section class="page" ref="page">
    <transition name="fade">
    <div class="question" v-if="ask" key="question">
        <h1 class="question__text">Are you a Middle Child?</h1>
        <ul class="question__list">
            <li class="question__item" @click="setAlbum($event)">Eldest Child</li>
            <li class="question__item" @click="setAlbum($event)">Middle Child</li>
            <li class="question__item" @click="setAlbum($event)">Youngest Child</li>
            <li class="question__item" @click="setAlbum($event)">Only Child</li>
        </ul>
    </div>
    <div class="overlay" v-else key="answer">
        <div class="overlay__name">
            <h2>J.Cole</h2>
        </div>
        <div class="overlay__title">
            <h1 class="overlay__headline">{{ childOrder }}</h1>
        </div>
        <div class="overlay__rating">
            <img src="~assets/labs/middle-child/parental-advisory.svg" class="logo">
        </div>
    </div>
    </transition>
    <canvas ref="static" id="canvas" width="600px" height="600px"></canvas>
  </section>
</template>

<script>

export default {
    data() {
        return {
            ask: true,
            childOrder: 'Middle Child',
        }
    },
    mounted() {
        this.noise(this.$refs.static)

        // animate static
        let toggle = true;
        const loop = () => {
            toggle = !toggle
            if (toggle) {
                setTimeout( function()  {
                    requestAnimationFrame(loop)
                }, 40)
                return
            }
            this.noise(this.$refs.static)
            requestAnimationFrame(loop)
        };

        loop()
    },
    methods: {
        setAlbum(answer) {
            this.ask = false
            console.log(answer.target.innerHTML)
            this.childOrder = answer.target.innerHTML

            this.$nextTick(() => {
                // separate letters
                const headline = new SplitText('.overlay__headline', {
                    type: 'chars',
                });
                // allow data to be passed to pseudos
                headline.chars.forEach( (e) => {
                    const letter = e.innerHTML
                    e.dataset.headline = letter
                    e.classList.add('overlay__letter')
                })
                // letter flickering
                setInterval( () => {
                    const l = headline.chars.length
                    const rand = Math.floor(Math.random() * l)
                    const e = headline.chars[rand]
                    e.style.opacity = Math.random()
                    setTimeout( function() {
                        e.style.opacity = 1
                    }, this.getRandomInt(800, 400))
                }, this.getRandomInt(1200, 300))
            });
        },
        noise(e) {
            const ctx = e.getContext('2d');
            ctx.clearRect(0, 0, 300, 150);
            let w = ctx.canvas.width,
                h = ctx.canvas.height,
                imageData = ctx.createImageData(w, h),
                l = imageData.data.length,
                i = 0;

            for(; i < l;)
                imageData.data[i++] = (155 * Math.random()) + 70 | 20;

            ctx.putImageData(imageData, 0, 0);
        },
        getRandomInt(max, min) {
            return Math.floor(Math.random() * Math.floor(max - min) + min)
        },
    },
}
</script>

<style scoped lang="scss">
@import '~assets/sass/utilities/_variables.scss';
$blue: #1AC5FD;
$red: #FE0000;

.page {
    color: white;
    background-color: #d8d8d8;
}
#canvas {
    display: block;
    width: 100%;
}
.overlay {
    position: absolute;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-between;
    width: 100%;
    height: 100%;
    padding: $spacing*2 $spacing;

    &__name {
        h2 {
            color: white;
            font-size: 1.375em;
            text-transform: uppercase;
            letter-spacing: 0.25em;
        }
    }
    &__title {
		position: relative;
		z-index: 100;
	}
    &__headline {
        font-size: 4.5rem;
        text-transform: uppercase;
        color: white;
    }
    & /deep/ .overlay__letter { // vue does not recognize these, bc/ they were generated by gsap.
        &:before {
            content: attr(data-headline);
            position: absolute;
            background: repeating-linear-gradient($red, $red 4px, transparent 0.75px, transparent 4.75px);
            background-clip: text;
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            filter: blur(0.625px);
            opacity: 0.25;
            transform: translateX(-5px);
            z-index: -1;
        }
        &:after {
            content: attr(data-headline);
            position: absolute;
            left: 0;
            background: repeating-linear-gradient($blue, $blue 4px, transparent 0.75px, transparent 4.75px);
            background-clip: text;
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            filter: blur(0.875px);
            mix-blend-mode: saturation;
            opacity: 0.5;
            transform: translateX(3px);
            z-index: 1;
        }
    }
    &__rating {
        max-width: 85px;
    }
}

.question {
    position: absolute;
    display: flex;
    justify-content: center;
    flex-direction: column;
    align-content: center;
    width: 100%;
    height: 100%;
    text-align: center;
    background-color: rgba(40, 40, 70, 0.6);
    &__list {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        width: 650px;
        margin: $spacing auto;
    }
    &__item {
        width: calc(50% - 30px);
        margin: $spacing/2;
        padding: $spacing/4;
        border: 1px solid white;
        list-style-type: none;
        cursor: pointer;
        transition: all 200ms $ease;
        &:hover {
            background-color: white;
            color: #686868;
        }
    }
}
</style>
